name: es-demo
services:
  search:
    type: elasticsearch:latest
    portforward: 9200
    config:
      server: config/elasticsearch.yml
  kibana:
    type: compose
    services:
      image: docker.elastic.co/kibana/kibana:latest
      ports:
        - "5601:5601"
#    config:
#      server: config/elasticsearch.yml