http:
  port: 9200
path:
  data: /bitnami/elasticsearch/data
  repo: /user/elasticsearch
transport:
  tcp:
    port: 9300
network:
  host: 172.25.0.3
  publish_host: 172.25.0.3
  bind_host: 0.0.0.0
cluster:
  name: bespin
node:
  name: lando
  master: true
  data: true
  ingest: false
discovery:
  type: single-node
